name: Go CI

on:
  push:
    branches-ignore:
      - renovate/**
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Push events to matching v*, i.e. v20.15.10
  pull_request:
    branches:
      - '**'

jobs:

  strongo_workflow:
    permissions:
      contents: write
    uses: strongo/go-ci-action/.github/workflows/workflow.yml@main
    with:
      install-firebase-tools: true
      GOOGLE_APPLICATION_CREDENTIALS: GOOGLE_APPLICATION_CREDENTIALS.json
    secrets:
      FIREBASE_PROJECT_ID: ${{ secrets.DALGO_E2E_PROJECT_ID }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
