on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # Push events to matching v*, i.e. v20.15.10
  pull_request:
    branches:
      - main
name: Vet, Test, Build
jobs:

  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4

      - run: go get ./...

      - name: go vet ./...
        run: go vet ./...

      - name: go build ./...
        run: go build ./...

      - name: Write GOOGLE_APPLICATION_CREDENTIALS to temp file
        run: |
          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode >> ${{ runner.temp }}/GOOGLE_APPLICATION_CREDENTIALS.json

      - name: Install Firebase tools
        run: curl -sL firebase.tools | bash

      - name: Test
        env:
          DALGO_E2E_PROJECT_ID: ${{ secrets.DALGO_E2E_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/GOOGLE_APPLICATION_CREDENTIALS.json
        run: go test ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

          args: --timeout=3m --print-issued-lines=true

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the all caching functionality will be complete disabled,
          #           takes precedence over all other caching options.
          # skip-cache: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true
