name: Go CI

on:
  push:
    branches:
      - main
      - renovate/**
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'
  pull_request:
    branches:
      - main

jobs:

  go_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'

      - name: Install Firebase tools
        run: curl -sL firebase.tools | bash

#      - name: Download Firebase tools @ v11.28.0
#        run: curl -Lo /usr/local/bin/firebase https://firebase.tools/bin/linux/v11.28.0
#
#      - name: Setup Firebase tools
#        run: sudo chmod +rx /usr/local/bin/firebase

      - uses: strongo/go-ci-action@v1.0.1
        env:
          DALGO_E2E_PROJECT_ID: ${{ secrets.DALGO_E2E_PROJECT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: ${{ runner.temp }}/GOOGLE_APPLICATION_CREDENTIALS.json
